#ifndef PERMISSIONS_H
#define PERMISSIONS_H

class Permissions
{
public:
    static const String TEMPERATURECONDITION_CREATE;
    static const String TEMPERATURECONDITION_UPDATE;
    static const String TEMPERATURECONDITION_DELETE;
    static const String TEMPERATURECONDITION_GET;
    static const String HUMIDITYCONDITION_CREATE;
    static const String HUMIDITYCONDITION_UPDATE;
    static const String HUMIDITYCONDITION_DELETE;
    static const String HUMIDITYCONDITION_GET;
    static const String LIGHTCONDITION_CREATE;
    static const String LIGHTCONDITION_UPDATE;
    static const String LIGHTCONDITION_DELETE;
    static const String LIGHTCONDITION_GET;
    static const String SOILMOISTURECONDITION_CREATE;
    static const String SOILMOISTURECONDITION_UPDATE;
    static const String SOILMOISTURECONDITION_DELETE;
    static const String SOILMOISTURECONDITION_GET;
    static const String CONDITION_CREATE;
    static const String CONDITION_UPDATE;
    static const String CONDITION_DELETE;
    static const String CONDITION_GET;
    static const String GREENHOUSE_CREATE;
    static const String GREENHOUSE_UPDATE;
    static const String GREENHOUSE_DELETE;
    static const String GREENHOUSE_GET;
    static const String PLANTTYPE_CREATE;
    static const String PLANTTYPE_UPDATE;
    static const String PLANTTYPE_DELETE;
    static const String PLANTTYPE_GET;
    static const String PLANT_CREATE;
    static const String PLANT_UPDATE;
    static const String PLANT_DELETE;
    static const String PLANT_GET;
    static const String GREENHOUSESENSOR_CREATE;
    static const String GREENHOUSESENSOR_UPDATE;
    static const String GREENHOUSESENSOR_DELETE;
    static const String GREENHOUSESENSOR_GET;
    static const String GREENHOUSECONTROL_CREATE;
    static const String GREENHOUSECONTROL_UPDATE;
    static const String GREENHOUSECONTROL_DELETE;
    static const String GREENHOUSECONTROL_GET;
    static const String TEMPERATURELOG_CREATE;
    static const String TEMPERATURELOG_UPDATE;
    static const String TEMPERATURELOG_DELETE;
    static const String TEMPERATURELOG_GET;
    static const String HUMIDITYLOG_CREATE;
    static const String HUMIDITYLOG_UPDATE;
    static const String HUMIDITYLOG_DELETE;
    static const String HUMIDITYLOG_GET;
    static const String LIGHTLOG_CREATE;
    static const String LIGHTLOG_UPDATE;
    static const String LIGHTLOG_DELETE;
    static const String LIGHTLOG_GET;
    static const String SOILMOISTURELOG_CREATE;
    static const String SOILMOISTURELOG_UPDATE;
    static const String SOILMOISTURELOG_DELETE;
    static const String SOILMOISTURELOG_GET;
    static const String GREENHOUSES_SWITCHMODULE;
    static const String GREENHOUSES_SETCONDITION;
    static const String PLANTS_SETPLANTCONDITION;
    static const String PLANTS_GETPLANTLOG;
    static const String LOGS_GETLOGSBYDATERANGE;
    static const String CONDITIONS_GETCURRENTCONDITIONS;


    static void addPermissions(Context* context);
};

void Permissions::addPermissions(Context* context)
{
    context->getSecurity()->addPermissionForAdmin(TEMPERATURECONDITION_CREATE, "Growify Permissions");
    context->getSecurity()->addPermissionForAdmin(TEMPERATURECONDITION_UPDATE, "Growify Permissions");
    context->getSecurity()->addPermissionForAdmin(TEMPERATURECONDITION_DELETE, "Growify Permissions");
    context->getSecurity()->addPermissionForAdmin(TEMPERATURECONDITION_GET, "Growify Permissions");
    context->getSecurity()->addPermissionForAdmin(HUMIDITYCONDITION_CREATE, "Growify Permissions");
    context->getSecurity()->addPermissionForAdmin(HUMIDITYCONDITION_UPDATE, "Growify Permissions");
    context->getSecurity()->addPermissionForAdmin(HUMIDITYCONDITION_DELETE, "Growify Permissions");
    context->getSecurity()->addPermissionForAdmin(HUMIDITYCONDITION_GET, "Growify Permissions");
    context->getSecurity()->addPermissionForAdmin(LIGHTCONDITION_CREATE, "Growify Permissions");
    context->getSecurity()->addPermissionForAdmin(LIGHTCONDITION_UPDATE, "Growify Permissions");
    context->getSecurity()->addPermissionForAdmin(LIGHTCONDITION_DELETE, "Growify Permissions");
    context->getSecurity()->addPermissionForAdmin(LIGHTCONDITION_GET, "Growify Permissions");
    context->getSecurity()->addPermissionForAdmin(SOILMOISTURECONDITION_CREATE, "Growify Permissions");
    context->getSecurity()->addPermissionForAdmin(SOILMOISTURECONDITION_UPDATE, "Growify Permissions");
    context->getSecurity()->addPermissionForAdmin(SOILMOISTURECONDITION_DELETE, "Growify Permissions");
    context->getSecurity()->addPermissionForAdmin(SOILMOISTURECONDITION_GET, "Growify Permissions");
    context->getSecurity()->addPermissionForAdmin(CONDITION_CREATE, "Growify Permissions");
    context->getSecurity()->addPermissionForAdmin(CONDITION_UPDATE, "Growify Permissions");
    context->getSecurity()->addPermissionForAdmin(CONDITION_DELETE, "Growify Permissions");
    context->getSecurity()->addPermissionForAdmin(CONDITION_GET, "Growify Permissions");
    context->getSecurity()->addPermissionForAdmin(GREENHOUSE_CREATE, "Growify Permissions");
    context->getSecurity()->addPermissionForAdmin(GREENHOUSE_UPDATE, "Growify Permissions");
    context->getSecurity()->addPermissionForAdmin(GREENHOUSE_DELETE, "Growify Permissions");
    context->getSecurity()->addPermissionForAdmin(GREENHOUSE_GET, "Growify Permissions");
    context->getSecurity()->addPermissionForAdmin(PLANTTYPE_CREATE, "Growify Permissions");
    context->getSecurity()->addPermissionForAdmin(PLANTTYPE_UPDATE, "Growify Permissions");
    context->getSecurity()->addPermissionForAdmin(PLANTTYPE_DELETE, "Growify Permissions");
    context->getSecurity()->addPermissionForAdmin(PLANTTYPE_GET, "Growify Permissions");
    context->getSecurity()->addPermissionForAdmin(PLANT_CREATE, "Growify Permissions");
    context->getSecurity()->addPermissionForAdmin(PLANT_UPDATE, "Growify Permissions");
    context->getSecurity()->addPermissionForAdmin(PLANT_DELETE, "Growify Permissions");
    context->getSecurity()->addPermissionForAdmin(PLANT_GET, "Growify Permissions");
    context->getSecurity()->addPermissionForAdmin(GREENHOUSESENSOR_CREATE, "Growify Permissions");
    context->getSecurity()->addPermissionForAdmin(GREENHOUSESENSOR_UPDATE, "Growify Permissions");
    context->getSecurity()->addPermissionForAdmin(GREENHOUSESENSOR_DELETE, "Growify Permissions");
    context->getSecurity()->addPermissionForAdmin(GREENHOUSESENSOR_GET, "Growify Permissions");
    context->getSecurity()->addPermissionForAdmin(GREENHOUSECONTROL_CREATE, "Growify Permissions");
    context->getSecurity()->addPermissionForAdmin(GREENHOUSECONTROL_UPDATE, "Growify Permissions");
    context->getSecurity()->addPermissionForAdmin(GREENHOUSECONTROL_DELETE, "Growify Permissions");
    context->getSecurity()->addPermissionForAdmin(GREENHOUSECONTROL_GET, "Growify Permissions");
    context->getSecurity()->addPermissionForAdmin(TEMPERATURELOG_CREATE, "Growify Permissions");
    context->getSecurity()->addPermissionForAdmin(TEMPERATURELOG_UPDATE, "Growify Permissions");
    context->getSecurity()->addPermissionForAdmin(TEMPERATURELOG_DELETE, "Growify Permissions");
    context->getSecurity()->addPermissionForAdmin(TEMPERATURELOG_GET, "Growify Permissions");
    context->getSecurity()->addPermissionForAdmin(HUMIDITYLOG_CREATE, "Growify Permissions");
    context->getSecurity()->addPermissionForAdmin(HUMIDITYLOG_UPDATE, "Growify Permissions");
    context->getSecurity()->addPermissionForAdmin(HUMIDITYLOG_DELETE, "Growify Permissions");
    context->getSecurity()->addPermissionForAdmin(HUMIDITYLOG_GET, "Growify Permissions");
    context->getSecurity()->addPermissionForAdmin(LIGHTLOG_CREATE, "Growify Permissions");
    context->getSecurity()->addPermissionForAdmin(LIGHTLOG_UPDATE, "Growify Permissions");
    context->getSecurity()->addPermissionForAdmin(LIGHTLOG_DELETE, "Growify Permissions");
    context->getSecurity()->addPermissionForAdmin(LIGHTLOG_GET, "Growify Permissions");
    context->getSecurity()->addPermissionForAdmin(SOILMOISTURELOG_CREATE, "Growify Permissions");
    context->getSecurity()->addPermissionForAdmin(SOILMOISTURELOG_UPDATE, "Growify Permissions");
    context->getSecurity()->addPermissionForAdmin(SOILMOISTURELOG_DELETE, "Growify Permissions");
    context->getSecurity()->addPermissionForAdmin(SOILMOISTURELOG_GET, "Growify Permissions");
    context->getSecurity()->addPermissionForAdmin(GREENHOUSES_SWITCHMODULE, "Growify Permissions");
    context->getSecurity()->addPermissionForAdmin(GREENHOUSES_SETCONDITION, "Growify Permissions");
    context->getSecurity()->addPermissionForAdmin(PLANTS_SETPLANTCONDITION, "Growify Permissions");
    context->getSecurity()->addPermissionForAdmin(PLANTS_GETPLANTLOG, "Growify Permissions");
    context->getSecurity()->addPermissionForAdmin(LOGS_GETLOGSBYDATERANGE, "Growify Permissions");
    context->getSecurity()->addPermissionForAdmin(CONDITIONS_GETCURRENTCONDITIONS, "Growify Permissions");

}

const String Permissions::TEMPERATURECONDITION_CREATE = "temperaturecondition_create";
const String Permissions::TEMPERATURECONDITION_UPDATE = "temperaturecondition_update";
const String Permissions::TEMPERATURECONDITION_DELETE = "temperaturecondition_delete";
const String Permissions::TEMPERATURECONDITION_GET = "temperaturecondition_get";
const String Permissions::HUMIDITYCONDITION_CREATE = "humiditycondition_create";
const String Permissions::HUMIDITYCONDITION_UPDATE = "humiditycondition_update";
const String Permissions::HUMIDITYCONDITION_DELETE = "humiditycondition_delete";
const String Permissions::HUMIDITYCONDITION_GET = "humiditycondition_get";
const String Permissions::LIGHTCONDITION_CREATE = "lightcondition_create";
const String Permissions::LIGHTCONDITION_UPDATE = "lightcondition_update";
const String Permissions::LIGHTCONDITION_DELETE = "lightcondition_delete";
const String Permissions::LIGHTCONDITION_GET = "lightcondition_get";
const String Permissions::SOILMOISTURECONDITION_CREATE = "soilmoisturecondition_create";
const String Permissions::SOILMOISTURECONDITION_UPDATE = "soilmoisturecondition_update";
const String Permissions::SOILMOISTURECONDITION_DELETE = "soilmoisturecondition_delete";
const String Permissions::SOILMOISTURECONDITION_GET = "soilmoisturecondition_get";
const String Permissions::CONDITION_CREATE = "condition_create";
const String Permissions::CONDITION_UPDATE = "condition_update";
const String Permissions::CONDITION_DELETE = "condition_delete";
const String Permissions::CONDITION_GET = "condition_get";
const String Permissions::GREENHOUSE_CREATE = "greenhouse_create";
const String Permissions::GREENHOUSE_UPDATE = "greenhouse_update";
const String Permissions::GREENHOUSE_DELETE = "greenhouse_delete";
const String Permissions::GREENHOUSE_GET = "greenhouse_get";
const String Permissions::PLANTTYPE_CREATE = "planttype_create";
const String Permissions::PLANTTYPE_UPDATE = "planttype_update";
const String Permissions::PLANTTYPE_DELETE = "planttype_delete";
const String Permissions::PLANTTYPE_GET = "planttype_get";
const String Permissions::PLANT_CREATE = "plant_create";
const String Permissions::PLANT_UPDATE = "plant_update";
const String Permissions::PLANT_DELETE = "plant_delete";
const String Permissions::PLANT_GET = "plant_get";
const String Permissions::GREENHOUSESENSOR_CREATE = "greenhousesensor_create";
const String Permissions::GREENHOUSESENSOR_UPDATE = "greenhousesensor_update";
const String Permissions::GREENHOUSESENSOR_DELETE = "greenhousesensor_delete";
const String Permissions::GREENHOUSESENSOR_GET = "greenhousesensor_get";
const String Permissions::GREENHOUSECONTROL_CREATE = "greenhousecontrol_create";
const String Permissions::GREENHOUSECONTROL_UPDATE = "greenhousecontrol_update";
const String Permissions::GREENHOUSECONTROL_DELETE = "greenhousecontrol_delete";
const String Permissions::GREENHOUSECONTROL_GET = "greenhousecontrol_get";
const String Permissions::TEMPERATURELOG_CREATE = "temperaturelog_create";
const String Permissions::TEMPERATURELOG_UPDATE = "temperaturelog_update";
const String Permissions::TEMPERATURELOG_DELETE = "temperaturelog_delete";
const String Permissions::TEMPERATURELOG_GET = "temperaturelog_get";
const String Permissions::HUMIDITYLOG_CREATE = "humiditylog_create";
const String Permissions::HUMIDITYLOG_UPDATE = "humiditylog_update";
const String Permissions::HUMIDITYLOG_DELETE = "humiditylog_delete";
const String Permissions::HUMIDITYLOG_GET = "humiditylog_get";
const String Permissions::LIGHTLOG_CREATE = "lightlog_create";
const String Permissions::LIGHTLOG_UPDATE = "lightlog_update";
const String Permissions::LIGHTLOG_DELETE = "lightlog_delete";
const String Permissions::LIGHTLOG_GET = "lightlog_get";
const String Permissions::SOILMOISTURELOG_CREATE = "soilmoisturelog_create";
const String Permissions::SOILMOISTURELOG_UPDATE = "soilmoisturelog_update";
const String Permissions::SOILMOISTURELOG_DELETE = "soilmoisturelog_delete";
const String Permissions::SOILMOISTURELOG_GET = "soilmoisturelog_get";
const String Permissions::GREENHOUSES_SWITCHMODULE = "greenhouses_switchmodule";
const String Permissions::GREENHOUSES_SETCONDITION = "greenhouses_setcondition";
const String Permissions::PLANTS_SETPLANTCONDITION = "plants_setplantcondition";
const String Permissions::PLANTS_GETPLANTLOG = "plants_getplantlog";
const String Permissions::LOGS_GETLOGSBYDATERANGE = "logs_getlogsbydaterange";
const String Permissions::CONDITIONS_GETCURRENTCONDITIONS = "conditions_getcurrentconditions";


#endif // PERMISSIONS_H
