#ifndef AUTHORIZATIONPERMISSIONS_H
#define AUTHORIZATIONPERMISSIONS_H

class AuthorizationPermissions
{
public:
    static const String USER_CREATE;
    static const String USER_UPDATE;
    static const String USER_DELETE;
    static const String USER_GET;
    static const String ROLE_CREATE;
    static const String ROLE_UPDATE;
    static const String ROLE_DELETE;
    static const String ROLE_GET;
    static const String PERMISSION_CREATE;
    static const String PERMISSION_UPDATE;
    static const String PERMISSION_DELETE;
    static const String PERMISSION_GET;
    static const String ROLEPERMISSION_CREATE;
    static const String ROLEPERMISSION_UPDATE;
    static const String ROLEPERMISSION_DELETE;
    static const String ROLEPERMISSION_GET;
    static const String USERRESETPASS_CREATE;
    static const String USERRESETPASS_UPDATE;
    static const String USERRESETPASS_DELETE;
    static const String USERRESETPASS_GET;
    static const String SECURITYQUESTION_CREATE;
    static const String SECURITYQUESTION_UPDATE;
    static const String SECURITYQUESTION_DELETE;
    static const String SECURITYQUESTION_GET;
    static const String SECURITYQUESTIONTITLE_CREATE;
    static const String SECURITYQUESTIONTITLE_UPDATE;
    static const String SECURITYQUESTIONTITLE_DELETE;
    static const String SECURITYQUESTIONTITLE_GET;
    static const String LOGINATTEMPT_CREATE;
    static const String LOGINATTEMPT_UPDATE;
    static const String LOGINATTEMPT_DELETE;
    static const String LOGINATTEMPT_GET;
    static const String ACCOUNTLOCKOUT_CREATE;
    static const String ACCOUNTLOCKOUT_UPDATE;
    static const String ACCOUNTLOCKOUT_DELETE;
    static const String ACCOUNTLOCKOUT_GET;
    static const String TWOFACTORAUTH_CREATE;
    static const String TWOFACTORAUTH_UPDATE;
    static const String TWOFACTORAUTH_DELETE;
    static const String TWOFACTORAUTH_GET;
    static const String ACCOUNTACTIVITYLOG_CREATE;
    static const String ACCOUNTACTIVITYLOG_UPDATE;
    static const String ACCOUNTACTIVITYLOG_DELETE;
    static const String ACCOUNTACTIVITYLOG_GET;
    static const String AUTHENTICATION_LOGIN;
    static const String AUTHENTICATION_PASSWORDRESET;
    static const String AUTHENTICATION_PASSWORDRESETCONFIRM;
    static const String AUTHENTICATION_TWOFACTORAUTH;
    static const String AUTHENTICATION_TWOFACTORAUTHCONFIRM;
    static const String AUTHENTICATION_ACCOUNTLOCK;
    static const String AUTHENTICATION_ACCOUNTUNLOCK;
    static const String AUTHENTICATION_SECURITYQUESTIONANSWER;
    static const String AUTHENTICATION_CONFIG_CREATE;
    static const String AUTHENTICATION_CONFIG_UPDATE;
    static const String AUTHENTICATION_CONFIG_SUBMIT;
    static const String AUTHENTICATION_CONFIG_DELETE;
    static const String AUTHENTICATION_CONFIG_GET;
    static const String SYSTEM_CONFIG_CREATE;
    static const String SYSTEM_CONFIG_UPDATE;
    static const String SYSTEM_CONFIG_SUBMIT;
    static const String SYSTEM_CONFIG_DELETE;
    static const String SYSTEM_CONFIG_GET;
    static const String TESTREQUESTS_ADDDATA;
    static const String TESTREQUESTS_GETDATA;
    static const String TESTREQUESTS_PUBLICREQUEST;

    static const String GetData;
    static const String AddData;
};

const String AuthorizationPermissions::USER_CREATE = "user_create";
const String AuthorizationPermissions::USER_UPDATE = "user_update";
const String AuthorizationPermissions::USER_DELETE = "user_delete";
const String AuthorizationPermissions::USER_GET = "user_get";
const String AuthorizationPermissions::ROLE_CREATE = "role_create";
const String AuthorizationPermissions::ROLE_UPDATE = "role_update";
const String AuthorizationPermissions::ROLE_DELETE = "role_delete";
const String AuthorizationPermissions::ROLE_GET = "role_get";
const String AuthorizationPermissions::PERMISSION_CREATE = "permission_create";
const String AuthorizationPermissions::PERMISSION_UPDATE = "permission_update";
const String AuthorizationPermissions::PERMISSION_DELETE = "permission_delete";
const String AuthorizationPermissions::PERMISSION_GET = "permission_get";
const String AuthorizationPermissions::ROLEPERMISSION_CREATE = "rolepermission_create";
const String AuthorizationPermissions::ROLEPERMISSION_UPDATE = "rolepermission_update";
const String AuthorizationPermissions::ROLEPERMISSION_DELETE = "rolepermission_delete";
const String AuthorizationPermissions::ROLEPERMISSION_GET = "rolepermission_get";
const String AuthorizationPermissions::USERRESETPASS_CREATE = "userresetpass_create";
const String AuthorizationPermissions::USERRESETPASS_UPDATE = "userresetpass_update";
const String AuthorizationPermissions::USERRESETPASS_DELETE = "userresetpass_delete";
const String AuthorizationPermissions::USERRESETPASS_GET = "userresetpass_get";
const String AuthorizationPermissions::SECURITYQUESTION_CREATE = "securityquestion_create";
const String AuthorizationPermissions::SECURITYQUESTION_UPDATE = "securityquestion_update";
const String AuthorizationPermissions::SECURITYQUESTION_DELETE = "securityquestion_delete";
const String AuthorizationPermissions::SECURITYQUESTION_GET = "securityquestion_get";
const String AuthorizationPermissions::SECURITYQUESTIONTITLE_CREATE = "securityquestiontitle_create";
const String AuthorizationPermissions::SECURITYQUESTIONTITLE_UPDATE = "securityquestiontitle_update";
const String AuthorizationPermissions::SECURITYQUESTIONTITLE_DELETE = "securityquestiontitle_delete";
const String AuthorizationPermissions::SECURITYQUESTIONTITLE_GET = "securityquestiontitle_get";
const String AuthorizationPermissions::LOGINATTEMPT_CREATE = "loginattempt_create";
const String AuthorizationPermissions::LOGINATTEMPT_UPDATE = "loginattempt_update";
const String AuthorizationPermissions::LOGINATTEMPT_DELETE = "loginattempt_delete";
const String AuthorizationPermissions::LOGINATTEMPT_GET = "loginattempt_get";
const String AuthorizationPermissions::ACCOUNTLOCKOUT_CREATE = "accountlockout_create";
const String AuthorizationPermissions::ACCOUNTLOCKOUT_UPDATE = "accountlockout_update";
const String AuthorizationPermissions::ACCOUNTLOCKOUT_DELETE = "accountlockout_delete";
const String AuthorizationPermissions::ACCOUNTLOCKOUT_GET = "accountlockout_get";
const String AuthorizationPermissions::TWOFACTORAUTH_CREATE = "twofactorauth_create";
const String AuthorizationPermissions::TWOFACTORAUTH_UPDATE = "twofactorauth_update";
const String AuthorizationPermissions::TWOFACTORAUTH_DELETE = "twofactorauth_delete";
const String AuthorizationPermissions::TWOFACTORAUTH_GET = "twofactorauth_get";
const String AuthorizationPermissions::ACCOUNTACTIVITYLOG_CREATE = "accountactivitylog_create";
const String AuthorizationPermissions::ACCOUNTACTIVITYLOG_UPDATE = "accountactivitylog_update";
const String AuthorizationPermissions::ACCOUNTACTIVITYLOG_DELETE = "accountactivitylog_delete";
const String AuthorizationPermissions::ACCOUNTACTIVITYLOG_GET = "accountactivitylog_get";
const String AuthorizationPermissions::AUTHENTICATION_LOGIN = "authentication_login";
const String AuthorizationPermissions::AUTHENTICATION_PASSWORDRESET = "authentication_passwordreset";
const String AuthorizationPermissions::AUTHENTICATION_PASSWORDRESETCONFIRM = "authentication_passwordresetconfirm";
const String AuthorizationPermissions::AUTHENTICATION_TWOFACTORAUTH = "authentication_twofactorauth";
const String AuthorizationPermissions::AUTHENTICATION_TWOFACTORAUTHCONFIRM = "authentication_twofactorauthconfirm";
const String AuthorizationPermissions::AUTHENTICATION_ACCOUNTLOCK = "authentication_accountlock";
const String AuthorizationPermissions::AUTHENTICATION_ACCOUNTUNLOCK = "authentication_accountunlock";
const String AuthorizationPermissions::AUTHENTICATION_CONFIG_CREATE = "authentication_config_create";
const String AuthorizationPermissions::AUTHENTICATION_CONFIG_UPDATE = "authentication_config_update";
const String AuthorizationPermissions::AUTHENTICATION_CONFIG_SUBMIT = "authentication_config_submit";
const String AuthorizationPermissions::AUTHENTICATION_CONFIG_DELETE = "authentication_config_delete";
const String AuthorizationPermissions::AUTHENTICATION_CONFIG_GET = "authentication_config_get";
const String AuthorizationPermissions::SYSTEM_CONFIG_CREATE = "system_config_create";
const String AuthorizationPermissions::SYSTEM_CONFIG_UPDATE = "system_config_update";
const String AuthorizationPermissions::SYSTEM_CONFIG_SUBMIT = "system_config_submit";
const String AuthorizationPermissions::SYSTEM_CONFIG_DELETE = "system_config_delete";
const String AuthorizationPermissions::SYSTEM_CONFIG_GET = "system_config_get";
const String AuthorizationPermissions::AUTHENTICATION_SECURITYQUESTIONANSWER = "authentication_securityquestionanswer";
const String AuthorizationPermissions::TESTREQUESTS_ADDDATA = "testrequests_adddata";
const String AuthorizationPermissions::TESTREQUESTS_GETDATA = "testrequests_getdata";
const String AuthorizationPermissions::TESTREQUESTS_PUBLICREQUEST = "testrequests_publicrequest";

const String AuthorizationPermissions::GetData = "get_data";
const String AuthorizationPermissions::AddData = "add_data";

#endif // AUTHORIZATIONPERMISSIONS_H
